// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXPIE70N6yuJGf7wLCoExT5ag27Ll4Zg',
    appId: '1:597870954961:web:b051c7f6f9c18ae5d1f8f0',
    messagingSenderId: '597870954961',
    projectId: 'inventory-25032',
    authDomain: 'inventory-25032.firebaseapp.com',
    storageBucket: 'inventory-25032.appspot.com',
    measurementId: 'G-N3M83W073K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt1d8c0hze4cjLeOugasxO8x7uQYQiINQ',
    appId: '1:597870954961:android:e86845852aa95c38d1f8f0',
    messagingSenderId: '597870954961',
    projectId: 'inventory-25032',
    storageBucket: 'inventory-25032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TtUJtNXpeMU6pieIHgrcJQcO19ZVD-8',
    appId: '1:597870954961:ios:cdcd6cfc89426237d1f8f0',
    messagingSenderId: '597870954961',
    projectId: 'inventory-25032',
    storageBucket: 'inventory-25032.appspot.com',
    androidClientId: '597870954961-a9mrpvg330fdso71cu2pfbvbooepk0tn.apps.googleusercontent.com',
    iosClientId: '597870954961-82ddh3se5miphg1qvgbsnebr0rjseslc.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TtUJtNXpeMU6pieIHgrcJQcO19ZVD-8',
    appId: '1:597870954961:ios:cdcd6cfc89426237d1f8f0',
    messagingSenderId: '597870954961',
    projectId: 'inventory-25032',
    storageBucket: 'inventory-25032.appspot.com',
    androidClientId: '597870954961-a9mrpvg330fdso71cu2pfbvbooepk0tn.apps.googleusercontent.com',
    iosClientId: '597870954961-82ddh3se5miphg1qvgbsnebr0rjseslc.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryManagement',
  );
}
